// Zentrale Definition der fest definierten Kategorien
export const FIXED_CATEGORIES = [
  "Produktsuche und -auswahl",
  "Produktdarstellung",
  "Produktkonfiguration",
  "Check-out",
  "After Sales",
  "Lead Generation & Qualifizierung",
  "Discovery & Bedarfsanalyse",
  "Lösungskonzeption & Angebotserstellung",
  "Vertrags- & Procurement-Prozess",
  "Projekt-Kick-off & Onboarding",
  "Service-Delivery & Betrieb",
  "Training & Enablement",
  "Account-Management & Customer Success",
  "Abrechnung & Billing",
  "Contract Renewal & Expansion",
  "Offboarding & Transition",
  "Maintenance",
  "Support",
]
